
name: Build test and deploy Library App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository  
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies    
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install 
    - name: Start the server
      run : npm run start-be &
    - name: Serve html file
      run: npm start-fe &  
    - name: Execute the UI tests
      run: npm test

  deploy_server:
    if: github.ref == 'refs/heads/main'
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
        
  deploy_static_html:
    if: github.ref == 'refs/heads/main'
    needs: deploy_server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID_STATIC }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}        

